version: 2.1

jobs:
  sync-databricks-repo: 
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Pull changes to Repo
          command: |
            pip install databricks-cli
            databricks repos update --path /Repos/marshall.carter@databricks.com/transformers --branch master

workflows:
  main: 
    jobs:
      - sync-databricks-repo
